### ISSUE TITLE
config.yaml issues

### ISSUE THREAD

**Issue by ngmisl** [onwidget/astrowind#292]
I'm experiencing some strange issues in the latest release,

eg.

in config.yaml  

```
site:
  name: Website
  site: 'https://website.net'
  base: '/'
  trailingSlash: false
```

and for example in Logo.astro 

```
---
import { SITE } from '~/utils/config';
---

<span
  class="self-center ml-2 rtl:ml-0 rtl:mr-2 text-2xl md:text-xl font-bold text-gray-900 whitespace-nowrap dark:text-white"
>
  🚀 {SITE?.name}{SITE?.name}{SITE?.name}{SITE?.name}
</span>
```

it SHOULD change the sitename based on the config.yaml, but doesn't. also color changes are no longer applied correctly. Idk what's going on, if I fork the template now, config.yamls seems completely broken/not read
