### ISSUE TITLE
How you are using i18n

### ISSUE THREAD

**Issue by FuryCraft** [onwidget/astrowind#326]
Hi, I saw a line in src/config.yaml for i18n
``` yaml
i18n:
  language: en
  textDirection: ltr
  ```
  
But i don't really understand how you are using it, because you have no docs and docs from Astro are not sing the same method for i18n. So how I can translate my website in other languages like french and english, and have routes like this exemple

site.com/home -> site.com/fr/accueil

With one file
