### ISSUE TITLE
How to set the blog as home page?

### ISSUE THREAD

**Issue by ghidoz** [onwidget/astrowind#569]
I tried to set the posts list as home page by simply changing the `pathname` in the `config.yaml`:

```
    list:
      isEnabled: true
      pathname: ''
      robots:
        index: true
```

What's weird is that if I serve it locally with `npm start`, it works, but when I build it, then the index is the one in `pages/index.astro`.

If I copy the content of `pages/[...blog]/[...page].astro` into `pages/index.astro`, it complains:

> Cannot read properties of undefined (reading 'currentPage')

I guess because pagination is not enabled on the home page.

Anybody knows how to solve it? I haven't found anything online and it should be a pretty common request, no?

Thanks in advance
