### ISSUE TITLE
Generate blog content inside of blog folder 

### ISSUE THREAD

**Issue by Alaev** [onwidget/astrowind#76]
First of all thank for the cool repo!

Idea:

Looking at the build folder how the blog post were generated,
![Screenshot from 2023-01-05 14-07-14](https://user-images.githubusercontent.com/3925474/210776829-5e5820d8-4867-46f2-bdad-aeceb15e7693.png)

I have read multiple time that google is also using the folder structure to index the content.
![image](https://user-images.githubusercontent.com/3925474/210784603-0b7b8d24-8b4d-40e2-abfe-9f7142f97a65.png)

is there a more general solution to generate the blog content inside of blog folder?

**Comment by Alaev** [comment]
Ohhhh, haven't seen the config.mjs... 🤦

Yea Now I see the Blog object. Nice!

**Comment by natguy** [comment]
Hello. Thanks for the great Astro theme. Follow up issues I'm seeing on naming the blog section, especially the tags and categories:

Adding /blog/ to the paths:

1. The above BLOG.post.pathname no longer seems to work. What does seem to work: BLOG.post.permalink:

`post: {
      permalink: '/blog/%slug%', 
      noindex: false,
      disabled: false,
    },`
    
2. BUT, there does not seem to be a way to do the same for the tag and category urls. 

This does not fully work:

`tag: {
      pathname: 'blog/tag', 
      noindex: true,
      disabled: false,
    },`
    
Yes, you can add the 'blog/' folder name to the BLOG.tag.pathname for example, and it will update the tag links, but clicking those links will not resolve to a working tag page. The template does not seem to understand anything other than root level example.com/tag/lorem and example.com/category/ipsum.

The expectation is having the entire blog system (list, post, tag, category) either a) at the root or b) under the same folder name, but not mixed between the two.

Ideally, I could just manually rename the pages.[...blog] folder name to the desired 'blog' name (with the added benefit of not getting routing warnings when other, non-blog folders in the site are accessed), but that seems to open up a can of worms and breaks things.

Thoughts? Thanks!

**Comment by natguy** [comment]
I think I see what's going on. The whole blog, tag, category structure does not seem to work with "all blog elements in a folder" because: 

The [...blog] route parameter that is used to build the static pages is being used as BOTH a blog folder like 'example.com/BLOG/some-post' in the cases of blog list and blog posts AND the 'tag' and 'category' folders in teh case of 'example.com/TAG/some-tag' and so that blog param is unable to do both: 'example.com/BLOG/TAG/some-tag'

This is because the file structure does not account for tag and category parent folders? But this does:

pages/[...blog]/tag/[tag]/[...page.astro]

?

And so, we'd have to:

1. Add 'tag' and 'category' folders:
- pages/[...blog]/tag/[tag]/[...page.astro]
- pages/[...blog]/category/[category]/[...page.astro]

2. Change utils/permalinks.ts to be able to add BLOG_BASE to everything blog related:

```
export const BLOG_BASE = cleanSlug(BLOG?.list?.pathname);

let blog_base_path
if (BLOG_BASE !== '') {
  blog_base_path = BLOG_BASE + '/';
}

export const POST_PERMALINK_PATTERN = trimSlash('/' + blog_base_path + BLOG?.post?.permalink || '/%slug%');
export const CATEGORY_BASE = cleanSlug(blog_base_path + BLOG?.category?.pathname || 'category');
export const TAG_BASE = cleanSlug(blog_base_path + BLOG?.tag?.pathname) || 'tag';
```

3. Which means slight tweaks to the config:

```
 blog: {
    disabled: false,
    postsPerPage: 4,

    list: {
      pathname: 'learn', // Blog main path, you can change this to "articles" (/articles) or other
      noindex: false,
      disabled: false,
    },

    post: {
      permalink: '%slug%', // Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      noindex: false,
      disabled: false,
    },

    category: {
      pathname: 'category', // Category main path /category/some-category. Change to what you manually change [...blog]/category/ folder to.
      noindex: true,
      disabled: false,
    },

    tag: {
      pathname: 'tag', // Tag main path /tag/some-tag. Change to what you manually change [...blog]/tag/ folder to.
      noindex: true,
      disabled: false,
    },
  },
  ```

3. Change [tag][...page].astro and [category][...page].astro pages:

Import BLOG_BASE instead of TAG_BASE or CATEGORY_BASE:

`import { BLOG_BASE } from '~/utils/permalinks';`

And change from:  
`params: { tag: tag, blog: TAG_BASE || undefined },`

To:
`params: { tag: tag, blog: BLOG_BASE || undefined },`

Now, the pages will look to example.com/WhateverIsHere for your blog base name, even for tag and cat pages.

**Comment by akoskm** [comment]
@natguy I had the same requirement and simply wanted to show blog posts like `/blog/post-1`.

I started going down the same route and updated some of the path utils, but figured none of this is required in the latest 
version of this template [v0.9.9](https://github.com/onwidget/astrowind/releases/tag/v0.9.9).

This is the only line that needs to be updated

https://github.com/onwidget/astrowind/blob/1c2ff0f591d2c76b8cc719c296f2c87cb21930c6/src/config.yaml#L41

and changed to:

```
      permalink: '/blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
```

I hope this helps others who want blog posts to show up under the `/blog/` path.

**Comment by akoskm** [comment]
@prototypa can you help me understand why the default configuration already has the `/blog/%slug` form:

https://github.com/onwidget/astrowind/blob/1c2ff0f591d2c76b8cc719c296f2c87cb21930c6/src/utils/config.ts#L141C33-L141C33

but `src/config.yaml` has simply `/%slug%`.

If I want blog posts to appear correctly as `/blog/%slug%`, are there any more places where I have to make a change?

**Comment by prototypa** [comment]
Hi @natguy and @akoskm 

Sorry for the delay in responding. We were working on a very complex project and it took up all of our time. We're back.

If you want to have all blog routes inside `/blog`, all you need to do is update [config.yaml](https://github.com/onwidget/astrowind#configuration) with this:

```yaml
# ...

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: 'blog/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'blog/category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'blog/tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false
```
